# Site settings
title: DMPwerkzeug
description: ""
baseurl: ""
url: "http://dmpwerkzeug.github.io"

# Build settings
markdown: kramdown
permalink: pretty

navigation:
- title: Projektbeschreibung
  url: '/#overview'
- title: Arbeitspakete
  url: '/#workpackages'
- title: Team
  url: '/#team'

team:
- name: Claudia Engelhardt
  info: ist wissenschaftliche Mitarbeiterin and der Fachhochschule Potsdam (FHP) und der Niedersächsische Staats- und Universitätsbibliothek Göttingen (SUB).
  image: /img/team/ce.jpg
- name: Jochen Klar
  info: ist wissenschaftlicher Mitarbeiter am Leibniz-Institut für Astrophysik Potsdam (AIP). Dort Arbeitet er sowohl an der Entwicklung und dem Betrieb von astronomischen Datenbanken, sowie an interdisziplinären Projekten zu den Themen Datenmanagement und Datenveröffentlichungen.
  image: /img/team/jk.jpg
- name: Jens Ludwig
  info: ist wissenschaftlicher Mitarbeiter an der Staatsbibliothek zu Berlin.
  image: /img/team/jl.jpg
- name: Harry Enke
  info: leitet die E-Science Gruppe am Leibniz-Institut für Astrophysik Potsdam (AIP). Sein Arbeitsgebiet ist der Aufbau von digitaler Infrastruktur für Forschungsdaten in der Astrophysik. Er war als PI des Astrogrid-D am Aufbau des akademischen D-Grids beteiligt und ist Mitglied des German Astrophysics Virtual Observatory (GAVO).
  image: /img/team/he.jpg
- name: Heike Neuroth
  info: ist Professorin für Bibliothekswissenschaften an der Fachhochschule Potsdam (FHP). Ihr Arbeitsgebiet umfasst zahlreiche Aktivitäten im Bereich der elektronischen Archivierung, des Forschungsdatenmanagements, der langzeitarchivieung und den Digital Humanities.
  image: /img/team/hn.jpg

partner:
- name: Leibniz-Institut für Astrophysik Potsdam (AIP)
  link: http://www.aip.de
  info: Lorem ipsum ...
  logo: /img/partner/aip.jpg
- name: Fachhochschule Potsdam
  link: www.fh-potsdam.de
  info: Lorem ipsum ...
  logo: /img/partner/fhp.jpg
- name: Niedersächsische Staats- und Universitätsbibliothek Göttingen
  link: http://www.sub.uni-goettingen.de
  info: Lorem ipsum ...
  logo: /img/partner/sub.jpg
- name: Staatsbibliothek zu Berlin
  link: http://staatsbibliothek-berlin.de
  info: Lorem ipsum ...
  logo: /img/partner/sbb.jpg
- name: Deutsche Forschungsgemeinschaft
  link: http://www.dfg.de
  info: Lorem ipsum ...
  logo: /img/partner/dfg.jpg

