# Site settings
title: DMPwerkzeug
description: ""
baseurl: ""
#baseurl: "/dmpwerkzeug/github-page/"
url: "http://dmpwerkzeug.github.io"

# Build settings
markdown: kramdown
permalink: pretty

navigation:
- title: Projekt
  url: ''
- title: Arbeitspakete
  url: arbeitspakete
- title: Vernetzung
  url: vernetzung
- title: Kooperationen
  url: kooperationen
- title: Team
  url: team
