# Site settings
title: DMPwerkzeug
description: ""
baseurl: "/dmpwerkzeug/github-page/"
url: "http://dmpwerkzeug.github.io"

# Build settings
markdown: kramdown
permalink: pretty

navigation:
- title: Projekt
  url: ''
- title: Arbeitspakete
  url: arbeitspakete
- title: Vernetzung
  url: vernetzung
- title: Kooperationen
  url: kooperationen
- title: Team
  url: team


partner:
- name: Leibniz-Institut für Astrophysik Potsdam (AIP)
  link: http://www.aip.de
  info: Lorem ipsum ...
  logo: /img/partner/aip.jpg
- name: Fachhochschule Potsdam
  link: www.fh-potsdam.de
  info: Lorem ipsum ...
  logo: /img/partner/fhp.jpg
- name: Niedersächsische Staats- und Universitätsbibliothek Göttingen
  link: http://www.sub.uni-goettingen.de
  info: Lorem ipsum ...
  logo: /img/partner/sub.jpg
- name: Deutsche Forschungsgemeinschaft
  link: http://www.dfg.de
  info: Lorem ipsum ...
  logo: /img/partner/dfg.jpg
