# Site settings
title: RDMO
description: ""
baseurl: ""
url: "http://rdmorganiser.github.io"

# Build settings
markdown: kramdown
permalink: pretty

navigation:
- title: Projekt
  url: /
- title: Arbeitspakete
  url: /arbeitspakete
- title: Vernetzung
  url: /vernetzung
- title: Kooperationen
  url: /kooperationen
- title: Team
  url: /team
