# Site settings
title: DMPwerkzeug
description: ""
baseurl: ""
url: "http://dmpwerkzeug.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# navigation:
# - title: Projektbeschreibung
#   url: '/#overview'
# - title: Arbeitspakete
#   url: '/#workpackages'
# - title: Team
#   url: '/#team'
# - title: Partner
#   url: '#partner'

navigation:

team:
- name: Claudia Engelhardt
  affiliation: FH Potsdam / SUB Göttingen
  info: Lorem ipsum ...
  image: /img/team/ce.jpg
- name: Jochen Klar
  affiliation: Leibniz-Institut für Astrophysik Potsdam (AIP)
  info: Lorem ipsum ...
  image: /img/team/jk.jpg
- name: Jens Ludwig
  affiliation: Staatsbibliothek zu Berlin
  info: Lorem ipsum ...
  image: /img/team/jl.jpg
- name: Harry Enke
  affiliation: Leibniz-Institut für Astrophysik Potsdam (AIP)
  info: Lorem ipsum ...
  image: /img/team/he.jpg
- name: Heike Neuroth
  affiliation: FH Potsdam
  info: Lorem ipsum ...
  image: /img/team/hn.jpg

partner:
- name: Leibniz-Institut für Astrophysik Potsdam (AIP)
  link: http://www.aip.de
  info: Lorem ipsum ...
  logo: /img/partner/aip.jpg
- name: Fachhochschule Potsdam
  link: www.fh-potsdam.de
  info: Lorem ipsum ...
  logo: /img/partner/fhp.jpg
- name: Niedersächsische Staats- und Universitätsbibliothek Göttingen
  link: http://www.sub.uni-goettingen.de
  info: Lorem ipsum ...
  logo: /img/partner/sub.jpg
- name: Staatsbibliothek zu Berlin
  link: http://staatsbibliothek-berlin.de
  info: Lorem ipsum ...
  logo: /img/partner/sbb.jpg
- name: Deutsche Forschungsgemeinschaft
  link: http://www.dfg.de
  info: Lorem ipsum ...
  logo: /img/partner/dfg.jpg

